#!/bin/sh

# SimSoC-Cert, a Coq library on processor architectures for embedded systems.
# See the COPYRIGHTS and LICENSE files.

name=SimSoCCert

prog=`basename $0`

usage () { echo "usage: $prog [-h]"; }

help () {
  cat <<EOF
Creates an index for $name files in doc/main.html.

Options:
-h Provide this help and exit
EOF
}

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 0; then usage; exit 1; fi

doc=`pwd`/doc/main.html

cat doc/begin.html > $doc
echo "<ul>" >> $doc

for f in `ls *.v`
do
  g=`basename $f .v`
  echo "<li><a href=\"$name.$g.html\">$g</a></li>" >> $doc
done

echo "</ul>" >> $doc
cat doc/end.html >> $doc
