#!/bin/bash
SIMLIGHT="../simlight/simlight -d -i"
set -e # exit on error
set -x # verbose

$SIMLIGHT sum_iterative.elf -r0=903
$SIMLIGHT sum_recursive.elf -r0=903
$SIMLIGHT sum_direct.elf -r0=903
$SIMLIGHT arm_blx2.elf -r0=0x3
$SIMLIGHT arm_cflag.elf -r0=0xf
$SIMLIGHT arm_dpi.elf -r0=0x7ffff
$SIMLIGHT arm_edsp.elf -r0=0x7fffff
$SIMLIGHT arm_ldmstm.elf -r0=0x7
$SIMLIGHT arm_ldrd_strd.elf -r0=0xff
$SIMLIGHT arm_ldrstr.elf -r0=0x7ffffff
$SIMLIGHT arm_mrs.elf -r0=0x7ffff
$SIMLIGHT arm_msr.elf -r0=0x1ffff
$SIMLIGHT arm_multiple.elf -r0=0x3f
$SIMLIGHT arm_swi.elf -r0=0x3
$SIMLIGHT endian.elf -r0=0x7
$SIMLIGHT multiply.elf -r0=0xf
$SIMLIGHT simsoc_new1.elf -r0=0xff
$SIMLIGHT test_mem.elf -r0=0x3
$SIMLIGHT sorting.elf -r0=0x3f
# $SIMLIGHT crypto_short.elf -r0=0x7f
