#!/bin/sh

# SimSoC-Cert, a Coq library on processor architectures for embedded systems.
# See the COPYRIGHTS and LICENSE files.

prog=`basename $0`

usage () { echo "usage: $prog [-h] file.v"; }

help () {
  cat <<EOF
Extract OCaml file for file.v and compile it.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then args; fi

case $1 in
*.v) base=${1%.v};;
*) echo 'error: unknown file type'; exit 1;;
esac

echo generate Coq file for extracting $base.v ...
tmp=/tmp/extract_$base.v
echo "Require Extraction $base. Extraction Library $base." > $tmp

echo extract $base.ml ...
root=..
coqc -q -R $root/coq SimSoCCert -I $root/arm6 $tmp || exit $?
