# SimSoC-Cert, a toolkit for generating certified processor simulators
# See the COPYRIGHTS and LICENSE files.

include Makefile.common

OCAMLBUILD := ocamlbuild -j 2 -no-hygiene -no-links

ARM6_PARSING := indentation keepbincode keepoper oneline_expr parsebincode

TARGETS := simgen/main tools/dependot/dependot \
	$(ARM6_PARSING:%=arm6/parsing/%)

.PHONY: $(TARGETS)

$(TARGETS):
	$(SHOW) ocamlbuild $@
	$(HIDE) $(OCAMLBUILD) $@.d.byte $@.native \
		&& ln -f -s $(shell pwd)/_build/$@.native $@
