# SimSoC-Cert, a toolkit for generating certified processor simulators
# See the COPYRIGHTS and LICENSE files.

DIR := ../..

include $(DIR)/Makefile.common

default:
	$(BUILD) sh4/parsing/instr

clean::
	rm -f instr
