#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2009-11-06

prog=`basename $0`

usage () { echo "usage: $prog [-h]"; }

help () {
  cat <<EOF
Extract all OCaml files with ExtractArm6.v and compile them.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 0; then args; fi

echo remove tmp directory ...
rm -rf tmp
mkdir tmp
cd tmp
root=../..

echo extract OCaml files ...
coqc -q -R $root/coq SimSoCCert -I $root/arm6 ../ExtractArm6.v || exit $?

echo compute dependencies ...
ocamldep *.ml *.mli > .depend || exit $?
files=`ls *.ml | sed -e 's|.ml||g'`
order_deps=$root/tools/order_deps/order_deps
files=`sed -e 's|.cm[iox]||g' .depend | $order_deps $files`

echo create Makefile ...
sed -e "s|__FILES__|$files|" -e "s|__NAME__|extract|" ../Makefile.in > Makefile || exit $?

echo compile OCaml files ...
make -r -k
