#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2009-11-06

prog=`basename $0`
dir=`dirname $0`

usage () { echo "usage: $prog [-h]"; }

help () {
  cat <<EOF
Extract all OCaml files with Extraction.v and compile them.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 0; then args; fi

order_deps=../tools/order_deps/order_deps

rm -f *.ml *.mli
echo extract OCaml files ...
coqc -q -R ../coq SimSoCCert Extraction.v || exit $?
echo compute dependencies ...
ocamldep *.ml *.mli > .depend || exit $?
files=`ls *.ml | sed -e 's|.ml||g'`
files=`sed -e 's|.cm[iox]||g' .depend | $order_deps $files`
echo create Makefile ...
sed -e "s|__FILES__|$files|" -e "s|__NAME__|extract|" Makefile.in > Makefile || exit $?
echo compile OCaml files ...
make
